name: Greg Prisament
description: Blog - Greg Prisament
baseurl: "https://gregulator.github.io/blog"


#Author info
author_name: Greg Prisament

#contacts
author_github: https://github.com/gregulator
author_linkedin: http://www.linkedin.com/in/gregoryprisament
author_about: http://www.gregprisament.com/



#rendering settings
markdown: kramdown
pygments: true

relative_permalinks: false
permalink: /:year/:month/:day/:title.html


